server.port=8081

# Database configuration for AWS RDS
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Database connection pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=60000


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.root=INFO
logging.level.com.example.week4=DEBUG

# Suppress Hibernate SQL logs
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Configuration for Open Ai
spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.embedding.options.model="text-embedding-3-small"
