services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tariffdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 256MB
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tariffdb
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD:  ${POSTGRES_PASSWORD}
      MOACH_API_KEY: ${MOACH_API_KEY}
      SIGNING_SECRET: ${SIGNING_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_URL: jdbc:postgresql://postgres:5432/tariffdb?password=
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      TARIFF_URL: http://backend:8081
      JAVA_OPTS: -Xmx768m -Xms256m
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512MB
    restart: unless-stopped

  frontend:
    build: ./frontend/tarrif-project
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      

volumes:
  postgres_data: