services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tariffdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tariffdb
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD:  ${POSTGRES_PASSWORD}
      MOACH_API_KEY: ${MOACH_API_KEY}
      SIGNING_SECRET: ${SIGNING_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_URL: jdbc:postgresql://postgres:5432/tariffdb?password=
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      TARIFF_URL: http://backend:8081

  frontend:
    build: ./frontend/tarrif-project
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      

volumes:
  postgres_data: